export const mock_orders = [
  {
    order_id: "6548",
    created: "2 min ago",
    customer: "Joseph Wheeler",
    total: 61,
    profit: 14,
    percent: 14,
    status: "Pending",
  },
  {
    order_id: "6548",
    created: "10 min ago",
    customer: "Sarah Smith",
    total: 94,
    profit: 54,
    percent: 11,
    status: "Confirmed",
  },
  {
    order_id: "6548",
    created: "20 min ago",
    customer: "Larry Time",
    total: 84,
    profit: 24,
    percent: 10,
    status: "Processing",
  },
  {
    order_id: "6548",
    created: "45 min ago",
    customer: "Mary Jones",
    total: 65,
    profit: 14,
    percent: 9,
    status: "Picked",
  },
  {
    order_id: "6548",
    created: "2 hours ago",
    customer: "Michael Smith",
    total: 64,
    profit: 54,
    percent: 1,
    status: "Shipped",
  },
  {
    order_id: "6548",
    created: "4 hours ago",
    customer: "Barbara Banner",
    total: 124,
    profit: 54,
    percent: 8,
    status: "Delivered",
  },
  {
    order_id: "6548",
    created: "5 hours ago",
    customer: "Tim Lane",
    total: 65,
    profit: 5,
    percent: 13,
    status: "Pending",
  },
  {
    order_id: "6548",
    created: "8 hours ago",
    customer: "Peter Parrot",
    total: 64,
    profit: 4,
    percent: 2,
    status: "Pending",
  },
  {
    order_id: "6548",
    created: "9 hours ago",
    customer: "Claire Thompson",
    total: 64,
    profit: 54,
    percent: 56,
    status: "Pending",
  },
  {
    order_id: "6548",
    created: "12 hours ago",
    customer: "Terrence Chase",
    total: 12,
    profit: 53,
    percent: 16,
    status: "Pending",
  },
];

export const mock_products = [
  {
    product_name: "Lorem Ipsum",
    order_id: "6548",
    Quantity: 2,
    Price: 400.2,
  },
];
